DROP schema IF EXISTS gestion_educativa;

CREATE SCHEMA `gestion_educativa`;

USE gestion_educativa;

CREATE TABLE ALUMNOS
(
ID_ALUMNO int NOT NULL AUTO_INCREMENT primary KEY,
LEGAJO INT NOT NULL UNIQUE,
DNI INT NOT NULL UNIQUE,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
FECHA_NAC DATE NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONO VARCHAR(50) NOT NULL,
ESTADO INT DEFAULT 1
);



CREATE TABLE DOCENTE
(
ID_DOCENTE int NOT NULL AUTO_INCREMENT primary KEY,
LEGAJO INT NOT NULL UNIQUE,
DNI INT NOT NULL UNIQUE,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
FECHA_NAC DATE NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONO VARCHAR(50) NOT NULL,
ESTADO INT DEFAULT 1
);

CREATE TABLE USUARIOS
(
ID_USUARIO int NOT NULL AUTO_INCREMENT primary KEY,
NOMBRE VARCHAR(100),
PASS VARCHAR(100)
);

CREATE TABLE MATERIAS
(
ID_MATERIA INT NOT NULL auto_increment primary key,
NOMBRE_MATERIA VARCHAR(100)
);

CREATE TABLE CURSOS
(
ID_CURSO INT NOT NULL auto_increment primary key,
ID_MATERIA INT NOT NULL,
/*FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS(ID_MATERIA),*/
CUATRIMESTRE INT NOT NULL,
ANIO INT NOT NULL,
ID_DOCENTE INT NOT NULL,
/*CONSTRAINT FK_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTES(ID_DOCENTE)*/
ESTADO INT DEFAULT 1
);

CREATE TABLE ALUMNOS_CURSOS
(
ID_ALUMNOS_CURSOS INT NOT NULL auto_increment primary key,
ID_CURSO INT NOT NULL,
/*FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO),*/
ID_ALUMNO INT NOT NULL
/*FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO)*/
);

